baseURL: https://blog.deraco.fr/
title: Blog de Stéphane
theme: ananke


defaultContentLanguage: fr
defaultContentLanguageInSubdir: true

languages:
  en:
    title: Stéphane's Blog
    contentDir: ./content/en/
    languageCode: en
  fr:
    title: Blog de Stéphane
    contentDir: ./content/fr/
    languageCode: fr

params:
  show_reading_time: true
  twitter: https://twitter.com/stephane_deraco
  github: https://github.com/stephane-deraco
  linkedin: https://www.linkedin.com/in/st%C3%A9phane-deraco-964640194/
  featured_image: /images/elephants.jpg
  background_color_class: bg-dark-gray
  rss: true
  from: "2021"
  custom_css: [custom.css]
