baseURL: https://blog.deraco.fr/
languageCode: fr-fr
title: Blog de Stéphane
theme: ananke

DefaultContentLanguage: fr

params:
  show_reading_time: true
  twitter: https://twitter.com/stephane_deraco
  github: https://github.com/stephane-deraco